AllCops:
  Exclude:
    - 'bin/*'
    - 'config/application.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'

Metrics/LineLength:
  Max: 130
